version: "3"

services:
  wordpress-db:
    image: mariadb:latest
    networks:
      - wordpress-network
    volumes:
      - wordpress-db-volume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  wordpress:
    depends_on:
      - wordpress-db
    image: wordpress:latest
    networks:
      - wordpress-network
    volumes:
      - wordpress-volume:/var/www/html
    ports:
      - "8042:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
networks:
  wordpress-network:
volumes:
  wordpress-volume:
  wordpress-db-volume:
