version: "3"

services:
  mariadb:
    image: inception_mariadb:v1

    build:
      context: ./requirements/mariadb/

    container_name: mariadb

    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      inception_intra:
        ipv4_address: 172.10.0.42
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_general_ci
    restart: "always"

  wordpress:
    image: inception_wordpress:v1
    depends_on:
      - mariadb

    build:
      context: ./requirements/wordpress/

    container_name: wordpress

    volumes:
      - wordpress_volume:/var/www/html
    networks:
      inception_intra:
        ipv4_address: 172.10.0.41
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_ADMIN_NAME: ${WP_ADMIN_NAME}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER_NAME: ${WP_USER_NAME}
      WP_USER_PASSWORD: ${WP_USER_PASSWORD}
      WP_USER_EMAIL: ${WP_USER_EMAIL}
    restart: "always"

  nginx:
    image: inception_nginx:v1
    depends_on:
      - wordpress

    build:
      context: ./requirements/nginx/

    container_name: nginx

    volumes:
      - wordpress_volume:/var/www/html
    networks:
      inception_intra:
        ipv4_address: 172.10.0.40
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    restart: "always"
    ports:
      - "443:443"

volumes:
  mariadb_volume:
    name: mariadb_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME:-/home/yongjule}/data/db
  wordpress_volume:
    name: wordpress_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME:-/home/yongjule}/data/wordpress

networks:
  inception_intra:
    ipam:
      config:
        - subnet: 172.10.0.0/24
    name: inception_intra
